sensors:
  right_bins_camera:
    type: advanced_logical_camera
    visualize_fov: true
    pose:
      xyz: [-2.286, 2.96, 1.8]
      rpy: [pi, pi/2, 0]

  left_bins_camera:
    type: advanced_logical_camera
    visualize_fov: true
    pose:
      xyz: [-2.286, -2.96, 1.8]
      rpy: [pi, pi/2, 0]

  kts1_camera:
    type: advanced_logical_camera
    visualize_fov: true
    pose:
      xyz: [-1.3, -5.8, 1.8]
      rpy: [pi, pi/2, pi/2]
  
  kts2_camera:
    type: advanced_logical_camera
    visualize_fov: true
    pose:
      xyz: [-1.3, 5.8, 1.8]
      rpy: [pi, pi/2, -pi/2]
  
  breakbeam_conveyor:
      type: break_beam
      visualize_fov: true
      pose:
          xyz: [-0.410, 1, 0.915]
          rpy: [0, 0, pi]

  alc_conveyor:
      visualize_fov: true
      type: advanced_logical_camera
      pose:
          xyz: [-0.603, 2.75, 1.85]
          rpy: [pi, pi/2, 0]

  agv_4_camera:
      visualize_fov: true
      type: advanced_logical_camera
      pose:
          xyz: [-2.059, -4.807, 1.239]
          rpy: [pi, pi/2, 0]

  agv_3_camera:
      visualize_fov: true
      type: advanced_logical_camera
      pose:
          xyz: [-2.059, -1.204, 1.239]
          rpy: [pi, pi/2, 0]

  agv_2_camera:
      visualize_fov: true
      type: advanced_logical_camera
      pose:
          xyz: [-2.059, 1.204, 1.239]
          rpy: [pi, pi/2, 0]

  agv_1_camera:
      visualize_fov: true
      type: advanced_logical_camera
      pose:
          xyz: [-2.059, 4.807, 1.239]
          rpy: [pi, pi/2, 0]