time_limit: -1

kitting_trays: # Which kitting trays will be spawn
  tray_ids: [1, 3, 4] 
  slots: [2, 5, 4]

challenges:
  - faulty_part:
      order_id: 'Kitting_Order_1'
      quadrant1: true
      quadrant2: true
      quadrant3: true
      quadrant4: true

parts:
  bins: # bin params - 8 total bins each bin has nine total slots (1-9)
    bin2: 
      - type: 'regulator'
        color: 'green'
        slots: [1, 5, 9]
        rotation: 'pi/6'
      - type: 'sensor'
        color: 'blue'
        slots: [3, 7, 8]
        rotation: 'pi/6'
    bin1: 
      - type: 'regulator'
        color: 'green'
        slots: [1, 4, 5, 6, 8, 9]
        rotation: 'pi/2'
    bin5: 
      - type: 'battery'
        color: 'red'
        slots: [1, 6, 9]
        rotation: 'pi'
    bin6: 
      - type: 'pump'
        color: 'orange'
        slots: [6, 7, 5]
        rotation: '-pi/6'
  agvs:
    agv2:
      tray_id: 5
      parts:
        - type: 'battery'
          color: 'purple'
          quadrant: 1
          rotation: 'pi/2'

orders:
  - id: 'Kitting_Order_1'
    type: 'kitting'
    announcement:
      time_condition: 2
    priority: false
    kitting_task:
      agv_number: 2
      tray_id: 5
      destination: 'warehouse'
      # ---------------------------------
      # products:
      #   - type: 'regulator'
      #     color: 'green'
      #     quadrant: 3
      #   - type: 'regulator'
      #     color: 'green'
      #     quadrant: 4
      # ---------------------------------
      # products:
      #   - type: 'sensor'
      #     color: 'blue'
      #     quadrant: 2
      #   - type: 'regulator'
      #     color: 'green'
      #     quadrant: 4
        # ---------------------------------
      # ---------------------------------
      products:
        - type: 'pump'
          color: 'orange'
          quadrant: 1
        # - type: 'battery'
        #   color: 'red'
        #   quadrant: 2
        # - type: 'regulator'
        #   color: 'green'
        #   quadrant: 3
        # - type: 'sensor'
        #   color: 'blue'
        #   quadrant: 4
      # products:
      #   - type: 'regulator'
      #     color: 'green'
      #     quadrant: 1
      #   - type: 'regulator'
      #     color: 'green'
      #     quadrant: 2
      #   - type: 'regulator'
      #     color: 'green'
      #     quadrant: 3
      #   - type: 'regulator'
      #     color: 'green'
      #     quadrant: 4