# Trial Name: rwa4.yaml

# ENVIRONMENT SETUP

time_limit: -1 # options: -1 (no time limit) or number of seconds (max 500)

kitting_trays: # Which kitting trays will be spawn
  tray_ids: [0, 3] 
  slots: [4, 1]

challenges:
  - faulty_part:
      order_id: 'KITTING1'
      quadrant1: true
      quadrant2: true
      quadrant3: true
      quadrant4: true

parts:  
  bins: # bin params - 8 total bins each bin has nine total slots (1-9)
    bin1:
      - type: 'pump'
        color: 'red'
        slots: [7]
      # - type: 'regulator'
      #   color: 'green'
      #   slots: [4,1]
    bin2:
      - type: 'regulator'
        color: 'green'
        slots: [1,2,3,4,5,6]
    bin5:
      - type: 'sensor'
        color: 'orange'
        slots: [4,5,6]
    bin6:
      - type: 'battery'
        color: 'blue'
        slots: [4,5,6]
  agvs:
    agv3:
      tray_id: 5
      parts:
        - type: 'battery'
          color: 'purple'
          quadrant: 4
          rotation: 'pi/2'

orders:
  - id: 'KITTING1'
    type: 'kitting'
    announcement:
      time_condition: 2
    priority: true
    kitting_task:
      agv_number: 2
      tray_id: 3
      destination: 'warehouse'
      products:
        - type: 'battery'
          color: 'blue'
          quadrant: 2
        - type: 'regulator'
          color: 'green'
          quadrant: 1
        # - type: 'regulator'
        #   color: 'green'
        #   quadrant: 2
        # - type: 'sensor'
        #   color: 'orange'
        #   quadrant: 1
        # - type: 'pump'
        #   color: 'red'
        #   quadrant: 3

          