sensors:
    breakbeam_0:
        type: break_beam
        visualize_fov: true
        pose:
            xyz: [-0.35, 3, 0.95]
            rpy: [0, 0, pi]

    proximity_sensor_0:
        type: proximity
        visualize_fov: true
        pose:
            xyz: [-0.573, 2.84, 1]
            rpy: [pi/2, pi/6, pi/2]

    laser_profiler_0:
        type: laser_profiler
        visualize_fov: true
        pose:
            xyz: [-0.573, 1.486, 1.526]
            rpy: [pi/2, pi/2, 0]

    alc_kitting_tray_left:
        visualize_fov: true
        type: advanced_logical_camera
        pose:
            xyz: [-1.30, -6.21, 1.8]
            rpy: [pi, pi/2, 0]

    alc_kitting_tray_right:
        visualize_fov: true
        type: advanced_logical_camera
        pose:
            xyz: [-1.30, 6.2, 1.8]
            rpy: [pi, pi/2, 0]

    alc_bin_left:
        visualize_fov: true
        type: advanced_logical_camera
        pose:
            xyz: [-2.286, -2.96, 1.8]
            rpy: [pi, pi/2, 0]

    alc_bin_right:
        visualize_fov: true
        type: advanced_logical_camera
        pose:
            xyz: [-2.286, 3.01, 1.8]
            rpy: [pi, pi/2, 0]

    alc_conveyor:
        visualize_fov: true
        type: advanced_logical_camera
        pose:
            xyz: [-0.573, 0.00, 1.95]
            rpy: [pi, pi/2, 0]

    alc_agv_1:
        visualize_fov: true
        type: advanced_logical_camera
        pose:
            xyz: [-2.059, -4.807, 1.239]
            rpy: [pi, pi/2, 0]

    alc_agv_2:
        visualize_fov: true
        type: advanced_logical_camera
        pose:
            xyz: [-2.059, -1.204, 1.239]
            rpy: [pi, pi/2, 0]

    alc_agv_3:
        visualize_fov: true
        type: advanced_logical_camera
        pose:
            xyz: [-2.059, 1.204, 1.239]
            rpy: [pi, pi/2, 0]

    alc_agv_4:
        visualize_fov: true
        type: advanced_logical_camera
        pose:
            xyz: [-2.059, 4.807, 1.239]
            rpy: [pi, pi/2, 0]