sensors:
    breakbeam_conveyor:
        type: break_beam
        visualize_fov: true
        pose:
            xyz: [-0.410, 3.25, 0.915]
            rpy: [0, 0, pi]

    alc_conveyor:
        visualize_fov: true
        type: advanced_logical_camera
        pose:
            xyz: [-0.603, 2.75, 1.15]
            rpy: [pi, pi/2, 0]

    alc_kitting_tray_left:
        visualize_fov: true
        type: advanced_logical_camera
        pose:
            xyz: [-1.30, -6.21, 1.8]
            rpy: [pi, pi/2, 0]

    alc_kitting_tray_right:
        visualize_fov: true
        type: advanced_logical_camera
        pose:
            xyz: [-1.30, 6.2, 1.8]
            rpy: [pi, pi/2, 0]

    alc_bin_left:
        visualize_fov: true
        type: advanced_logical_camera
        pose:
            xyz: [-2.286, -2.96, 1.8]
            rpy: [pi, pi/2, 0]

    alc_bin_right:
        visualize_fov: true
        type: advanced_logical_camera
        pose:
            xyz: [-2.286, 3.01, 1.8]
            rpy: [pi, pi/2, 0]



    # alc_agv_1:
    #     visualize_fov: true
    #     type: advanced_logical_camera
    #     pose:
    #         xyz: [-2.059, -4.807, 1.239]
    #         rpy: [pi, pi/2, 0]

    # alc_agv_2:
    #     visualize_fov: true
    #     type: advanced_logical_camera
    #     pose:
    #         xyz: [-2.059, -1.204, 1.239]
    #         rpy: [pi, pi/2, 0]

    # alc_agv_3:
    #     visualize_fov: true
    #     type: advanced_logical_camera
    #     pose:
    #         xyz: [-2.059, 1.204, 1.239]
    #         rpy: [pi, pi/2, 0]

    # alc_agv_4:
    #     visualize_fov: true
    #     type: advanced_logical_camera
    #     pose:
    #         xyz: [-2.059, 4.807, 1.239]
    #         rpy: [pi, pi/2, 0]